### ISSUE TITLE
Have to double click after drag to show APBox

### ISSUE THREAD

**Issue by JulissaDantes** [SingularSound/openbbm#103]
When a fill which has AP enabled is copied, the pasted fill has AP enabled, but no settings input box. User needs to disable and enable AP of the fill in order for settings to appear. What should happen is that either the input box is displayed along with the check-mark or neither the check mark nor the input box are displayed.

**Comment by JulissaDantes** [comment]
Also here this will be fix:

When drop fill on top of another already set fill, saving and reopening the previously saved setting is removed.

**Comment by Kiroto** [comment]
Tested, everything working smoothly!

**Comment by JulissaDantes** [comment]
This will be closed after QC

**Comment by JulissaDantes** [comment]
@brennansingular This is ready to be tested on master, the release.zip file is already updated.

**Comment by brennansingular** [comment]
@JulissaDantes when pasting the original file's state is kept the same, if I had Fill 4 with AP enabled to play at bar 9, and paste that on Fill 2 with AP off and set to bar 1, the paste will not be AP enabled and when I enable it, it still reads bar 1. 
Also, copy and pasting one AP enabled fill to another is not carrying the bar number.
I think that settings within a block should follow it.

@DavidPackouz thoughts?

**Comment by brennansingular** [comment]
@JulissaDantes ignore my above comments was confused

Copy-pasting is not making the box disappear, so I guess that was the fix here? Or is it only an issue when dragging and dropping?

**Comment by JulissaDantes** [comment]
@brennansingular the issue here is when dragging and dropping the AP box of the fills goes to a state where the box to put the ap values is hidden but the checkbox is marked. What should happen is when swappin 2 fills of dragging one to an empty space n the same song it should keep its settings.
