### ISSUE TITLE
Bug Playing Trans Fill

### ISSUE THREAD

**Issue by JulissaDantes** [SingularSound/openbbm#109]
When transition fill is triggered manually (AP off), it crashes the program.

**Comment by JulissaDantes** [comment]
@brennansingular This is ready on master.

**Comment by brennansingular** [comment]
@JulissaDantes Now I just can't transition when holding on virtual BB, this is when all of AP is off? or just AP on the transition?

**Comment by brennansingular** [comment]
This is on the Virtual BB right? @JulissaDantes

**Comment by JulissaDantes** [comment]
@brennansingular Yes this is using the virtual bb pedal. this is when the song have the Autopilot box unchecked and the user holds the pedal for the transition to play

**Comment by brennansingular** [comment]
@JulissaDantes confirmed still happening
