### ISSUE TITLE
AP Outro fill ignored if last part has no fills

### ISSUE THREAD

**Issue by brennansingular** [SingularSound/openbbm#113]
Outro fill is not being played although it is set to play at a specific bar, this is only if the least song part has no fills loaded in.
![Screenshot (32)](https://user-images.githubusercontent.com/62663388/92141198-1a6c8c00-ede0-11ea-814a-65e867f1fee5.png)

**Comment by JulissaDantes** [comment]
@brennansingular in the picture there is no outro fill, please upload the image where the bug occurs

**Comment by brennansingular** [comment]
Shouldn't it end then, even without an outro? It isn't ending, I can try again with another song, thought I'm positive having an outro there had no effect

**Comment by brennansingular** [comment]
After adding outro, now the BB is transitioning back to p1
![Screenshot (33)](https://user-images.githubusercontent.com/62663388/92163295-7267ba80-ee01-11ea-8e2b-54a52f0f84ab.png)
 instead of ending

**Comment by JulissaDantes** [comment]
@brennansingular you should talk to Goran about that one the song restarting at the end. It was something he requested on the presence of a transition fill on the last part it will restart the song to part 1.

**Comment by brennansingular** [comment]
I see, so if there's a transition fill put there, it will always ignore the outro?

**Comment by brennansingular** [comment]
The issue is that the text says to end at a specific place, so it isn't logical for that to happen on user's end

**Comment by JulissaDantes** [comment]
Is there is no trans fill it should end, and if there is a transfill it should restart
