### ISSUE TITLE
5th Drum Fill Changes AP on Load

### ISSUE THREAD

**Issue by JulissaDantes** [SingularSound/openbbm#115]
The 3 bar long drum fill sometimes changes the set AP value on load

(Edit):
Is not because is 3 bars long, even if is only 1 bar long it changes the AP number as long as it is the 5TH drum fill

**Comment by JulissaDantes** [comment]
Here is the example:
[song.zip](https://github.com/SingularSound/openbbm/files/5176366/song.zip)

**Comment by brennansingular** [comment]
@JulissaDantes Sorry, I'm not clear what should happen,  Idownloaded your song file, I changed the 5th fill to another number, saved the project, closed it and reopened and the numbers did not change, is this the fix?

**Comment by JulissaDantes** [comment]
Yes @brennansingular , the fix is the number it had when it closed it should have when it opens again, what was happening: you saved AP=20 saved the program and when you opened it again the AP would be 345 or some crazy number like that.
