### ISSUE TITLE
Have to press play  twice to start song

### ISSUE THREAD

**Issue by JulissaDantes** [SingularSound/openbbm#13]
if no song is playing you need to press the pedal twice for it to start, or press the "Play" button and the pedal next. It needs to start playing on the first play.

**Comment by Kiroto** [comment]
IMO this works as intended. It sets the program on to Play Mode to start emulating the actual beatbuddy. The first pedal click or play button click starts emulation mode, so you can start setting up to actually play.
Might want to check in with PO, as I'm not 100% sure.

**Comment by JulissaDantes** [comment]
It should start playing as soon as either button(pedal or Play button) is pressed only once.
