### ISSUE TITLE
BB Manager does not downgrade

### ISSUE THREAD

**Issue by brennansingular** [SingularSound/openbbm#131]
Downloaded what was supposed to be version 1.7.0.0 but it is still version 1.8.0.0, this may be why I got this message on start up, not sure if this is a new bug, or related to #130 
![94489202-084cf600-01b2-11eb-9eb4-a12f533584a3](https://user-images.githubusercontent.com/62663388/94606482-89ff5b00-0268-11eb-82a9-40931b6b9833.png)

**Comment by JulissaDantes** [comment]
According to the conversation on #130 this cannot be replicated neither by developer nor the user, presumably was fixed by other development, or cause by the user by closing the BBM when is was processing a change or something of that nature. We'll be on the lookout in case it happens again.
