### ISSUE TITLE
AP song with no transition on last part and AP is off

### ISSUE THREAD

**Issue by brennansingular** [SingularSound/openbbm#135]
This was on an AP enabled song with no transition on the last part, I turned AP off on the BeatBuddy menu and this happened.

Because the AP song has no transition on the last part, giving an automatic transition is [causing the BB to get stuck in the transition mode and playback silence until you tap.](https://photos.app.goo.gl/kA3U87VNffDSet4E9)

![Screenshot (43)](https://user-images.githubusercontent.com/62663388/94611632-02b5e580-0270-11eb-9d0e-44df79d09a1f.png)

**Comment by JulissaDantes** [comment]
@iajrz shouldn't this issue be on the firmware repo?

**Comment by iajrz** [comment]
Indeed; closing -- working on organizing that effort right now, too.
