### ISSUE TITLE
AP Tapping to extend a part not read if a fill is currently  playing

### ISSUE THREAD

**Issue by brennansingular** [SingularSound/openbbm#136]
If you tap while a fill is playing on the BB[, the BB does not extend the current part](https://photos.app.goo.gl/8FinmNsYEVbnYN9a8), BB should still read the tap and extend the section.

**Comment by JulissaDantes** [comment]
@iajrz should this be on the firmware repo?

**Comment by JulissaDantes** [comment]
@brennansingular  is this a bug on the BB or the BBM?

**Comment by brennansingular** [comment]
I imagine it's a little bit of both, I was told it was better to put the BBM related BB issues here

**Comment by JulissaDantes** [comment]
Note:
When we use the word 'Fill' we are referring to the last fill before transition/next part

**Comment by bacol89** [comment]
@JulissaDantes This calls a second drumfill while the drumfill is playing ?

**Comment by bacol89** [comment]
This calls a second drumfill while the drumfill is playing ?

**Comment by JulissaDantes** [comment]
@bacol89 what it should do is reset the song, if a drum fill is playing it wont call another, since is already playing one.
