### ISSUE TITLE
AP fill Playback issues

### ISSUE THREAD

**Issue by brennansingular** [SingularSound/openbbm#139]
BeatBuddy will occasionally play the same MIDI file differently or remove beats from a fill or [play it back incorrectly.](https://photos.app.goo.gl/3yE624C76JfTFLQG7)

Sometimes the fill will play only part of it, sometimes the fill will de-sync the playback cutting a measure arbitrarily, the same MIDI files playback differently

Here is the project screen
![Screenshot (52)](https://user-images.githubusercontent.com/62663388/94622795-d9518580-0280-11eb-82d5-65d20bea7412.png)

**Comment by GoranRista** [comment]
Does it depend on in which position it is in? Does it always play the same as Fill#1 in any section, but differently as Fill 2 in any section?

**Comment by brennansingular** [comment]
It did seem to have some correlation between what part it was in, yeah

**Comment by JulissaDantes** [comment]
@iajrz I think this bug is on the wrong repo

**Comment by iajrz** [comment]
indeed @brennansingular this seems to be a Beatbuddy Firmware thing - let's move the convo there. <3
