### ISSUE TITLE
Logic of outro

### ISSUE THREAD

**Issue by brennansingular** [SingularSound/openbbm#140]
If last part main loop block says "Play outro at measure 8" it should play the outro, this is not the case if the last part has a transition, then the outro is ignored making the text inaccurate.

Also, there is no change in behavior whether the Transition block is AP enabled or it isn't
![Screenshot (53)](https://user-images.githubusercontent.com/62663388/94623885-3bab8580-0283-11eb-828d-a2fe6574c42f.png)

@GoranRista this logic needs to be fixed, maybe change the outro dialog text to disappear on the last part if there is a transition block present. If AP is not enabled on the transition block, the part should play over and over until there is a command manually entered, if the transition block is AP enabled it should transition automatically.

Thoughts on that?

**Comment by GoranRista** [comment]
As you will notice in your screenshot, the transition fill (while present) is not set to be triggered by the AP. It is there as a "spare" fill, only manually triggered by a user should they choose to go to the top. The logic in the screenshot looks OK. This is not a bug.
