### ISSUE TITLE
Startup & Loop autopilot transition inconsistency when there is no intro loop.

### ISSUE THREAD

**Issue by Kiroto** [SingularSound/openbbm#18]
### Steps to reproduce:

1. Use Autopilot 6/8
2. Set first loop's autopilot to trigger transition fill at the second measure, first beat. (2, 1)
3. Play the autopilot.
4. <Autopilot transitions at the third measure, from the third beat>
5. Trigger a transition.
6. <Autopilot transitions at the third measure, from the first beat>

These are two bugs, but this issue focuses on the inconsistency between two loops, not the inaccuracy of the measure/beat trigger.

### Result:
First transitions triggered late, others were consistent.

### Expected:
Transition is always triggered at the third (second) measure, from the first beat.

### Tester Notes:
This loop doesn't have an entrance "loop".

**Comment by Kiroto** [comment]
Confirmed this only happens whenever the song doesn't have an intro loop.

**Comment by Kiroto** [comment]
Able to reproduce in 4/4 with the following setup, based on AutoPilot 4/4
![image](https://user-images.githubusercontent.com/11585686/81075617-97cad300-8eb8-11ea-87f2-97f08313a07d.png)

(Switched some loops for under pressure loops, removed intro)
The AutoPilot is set for a transition fill on the first main loop at measure 1, beat 1
When the song is played, the transition fill will not play at measure 1 beat 1, instead it will play beats 2 - 5 (either one of the last 3 beats of the first bar or the first beat of the second bar).

Stopping midway through the first loop (or first transition) seems to affect the transition's starting beat.

**Comment by JulissaDantes** [comment]
Closed by PR #29
