### ISSUE TITLE
Autopilot's trigger inaccuracy.

### ISSUE THREAD

**Issue by Kiroto** [SingularSound/openbbm#19]
### Steps to reproduce:

1. Use Autopilot 6/8
2. Set first loop's autopilot to trigger transition fill at the second measure, first beat. (2, 1)
3. Play the autopilot.
4. <Autopilot transitions at the third measure, from the third beat> (This inconsistency is out of issue scope. [Refer to this issue instead](https://github.com/SingularSound/openbbm/issues/18))
5. Manually transition back to the first loop
6. <Autopilot transitions at the third measure, from the first beat> (consistent, we're looking at this)

### Another Test:

1. Use Autopilot 6/8
2. Set first loop's autopilot to trigger transition fill at the first measure, first beat (1, 1)
3. Play the autopilot.
4. <Autopilot transitions at the first measure, from the third beat>
5. Manually transition back to the first loop
6. <Autopilot transitions at the first measure, from the first beat> (As expected)

### Result:
On the first test, the transitions happen at the third measure.

### Expected:
Transition is always triggered at the second measure.

### Tester Notes:
This loop is 2 measures in length.
Setting the autopilot to trigger on the 2nd measure, 1st beat probably makes it repeat the whole loop (2 measures) before triggering on the 1st beat.
This is reinforced by the fact that this does not happen on AutoPilot 4/4, where the first main loop is one measure in length and behaves as expected.

**Comment by Kiroto** [comment]
Able to reproduce in 4/4 with the following setup, based on AutoPilot 4/4
![image](https://user-images.githubusercontent.com/11585686/81073274-669cd380-8eb5-11ea-8329-804bd0f3fbd4.png)

(Switched some loops for under pressure loops)
The AutoPilot is set for a transition fill on the first main loop at measure 1, beat 1
When the song is played, the transition fill will not play at measure 1 beat 1, instead it will play beats 2 - 5 (either one of the last 3 beats of the first bar or the first beat of the second bar).

Stopping midway through the first loop (or first transition) seems to affect the transition's starting beat.

**Comment by JulissaDantes** [comment]
Closed by PR #29
