### ISSUE TITLE
README asks for unavailable QT version on MacOs

### ISSUE THREAD

**Issue by ericraymond** [SingularSound/openbbm#32]
The readme requires installation of `brew install qt@5.5`, but this results in `No available formula with the name "qt@5.5"`

Later versions of XCode are incompatible with this version of qt.  This is the default on MacOS Mojave or greater.

https://github.com/Homebrew/homebrew-core/issues/32467

Can a more recent version of QT be used? Any reason to pin the QT version?

**Comment by iajrz** [comment]
When that part of the docs was written XCode 10.4 hadn't come out and I'd just upgraded the framework from mybe Qt 5.3 to 5.5. This is a bug in the docs, though, as we're using 5.12.4 on Windows, and it should also work on macos.

**Comment by iajrz** [comment]
@ericraymond can you please verify that changing that to 5.12.4 makes it work properly so we can do this?

**Comment by ericraymond** [comment]
@iajrz Not even getting past the first step of building.  Have logged another issue on the build issues ... presumably due to the change to QT version

**Comment by ericraymond** [comment]
The readme went from asking for a specific version of QT (which was no compatible with the current compiler tools from Apple) to not specifying any version that works?

Is there still a requirement for a specific old version of QT on MAc?   Has this been tested with the current tools on MacoS?

First use experience for someone building and running for the first time needs to be well documented.

**Comment by iajrz** [comment]
Sadly, this wasn't tested in Catalina; I'd written the Macos build docs a while ago, I think they were good up to Mojave. Some development is going on the Windows side; when that's stabilized or we free up some additional developer time, we'll address the README for macos. Of course, were someone to tinker and get it to work, their feedback would help us immensely.

**Comment by ericraymond** [comment]
It does not work on Mojave.

**Comment by iajrz** [comment]
I may have upgraded to Mojave after doing the setup.

**Comment by iajrz** [comment]
This is related to #34 and both will be addressed the same way.

**Comment by iajrz** [comment]
branch https://github.com/SingularSound/openbbm/tree/issue32 has better docs about this. We're not in the ideal state, but at least the current state is better reflected in the readme.
