### ISSUE TITLE
Update readme with info to setup libquazip and libMinini

### ISSUE THREAD

**Issue by ericraymond** [SingularSound/openbbm#33]
The readme has a rather cryptic requirement that will be foreign to many developers:

```To successfully run BBManager, you need a local installation of libquazip and libMinini.

Those should be installed at the ~/lib directory, because the OS looks for shared libraries there without any configuration; the files to be moved into that directory can be found in BBManager/libs/quazip/macx/release and BBManager/libs/minIni/macx/release respectively.
```

Can the readme provide a bit more support for where to locate these libraries.  Shouldn't `make install` handke this?

**Comment by JulissaDantes** [comment]
The `make install` should handle this. The directories specified on the readme are the same routes specified on the .pro file. Are they missing after running the  `make install`? 

If you need to perform more step than specified on the readme, please share them with the community to update the read me.

**Comment by ericraymond** [comment]
> The `make install` should handle this. 

If that's the case, the readme should make that clear.  I can't test that due to the other build issues.

**Comment by JulissaDantes** [comment]
Thank you for the suggestion, it will be pointed out in the readme.
