### ISSUE TITLE
Make the GPLv2 license explicit

### ISSUE THREAD

**Issue by iajrz** [SingularSound/openbbm#4]
This is the license: https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html
These are the instructions to applying it to the project:
https://www.gnu.org/licenses/gpl-howto.html

**Comment by JulissaDantes** [comment]
This is what needs to be done  to complete this issue:
- [ ] Get a copyright disclaimer from your employer or school.
- [ ] Give each file the proper copyright notices. Make sure to clearly identify which versions of the license users can use.
- [ ] Add a COPYING file with a copy of the GNU GPL or GNU AGPL.
- [ ] Also add a COPYING.LESSER file with a copy of the GNU LGPL, if you use that.
- [ ] Put a license notice in each file.
- [ ] (If using the AGPL) make the program offer copies of its source code.
