### ISSUE TITLE
Create a loop when there is no Trans Fill in last song part

### ISSUE THREAD

**Issue by JulissaDantes** [SingularSound/openbbm#43]
Usually (in manual mode), when user is playing the last section and they trigger a transition fill, the song goes to the beginning. We should keep that behavior for the AP.

If there is a transition in the last section, play it and go back to the top. The way, it is an infinite song loop. Outro fill then needs to be triggered manually.

If there is not transition fill at the last section, play the outro fill. If there is no outro fill, just end the song.

**Comment by Kiroto** [comment]
Issue is correctly fixed by PR #45
