### ISSUE TITLE
Handle 0 as AP value

### ISSUE THREAD

**Issue by JulissaDantes** [SingularSound/openbbm#54]
Until we implement a new GUI for AP, we can have a setting of 0 for drum fills, which means that AP is off for them. That way if you program them, but later decide that you don't want to program them, you can set them to 0 and they won't play on their own.

**Comment by Kiroto** [comment]
Setting an AP Drum fill to 1st measure, 1st beat and saving will display said drum fill's AP setting as 0 on the AP form. (although it still behaves as if it was 1)
