### ISSUE TITLE
Edit Song Part Name

### ISSUE THREAD

**Issue by JulissaDantes** [SingularSound/openbbm#67]
Above each main beat part, create some space and display editable part names. They should be created by default as "Part 1, Part 2, Part 3...". Double-clicking the titles allows them to be edited. This is part of #63 .

**Comment by brennansingular** [comment]
![Screen Shot 2020-06-29 at 1 12 56 PM](https://user-images.githubusercontent.com/62663388/88099256-eeb38080-cb68-11ea-9743-a21f86664d45.png)
I think this request is in-line with this issue, we have already opened a similar issue to look into in the BB firmware repo

**Comment by JulissaDantes** [comment]
All part name will be editable, only the default will be its row number "Part #".

**Comment by JulissaDantes** [comment]
User reports Crashed editing 4th part. Editing the first song of the autopilot songs folder
