### ISSUE TITLE
Deployment documentation

### ISSUE THREAD

**Issue by saviourofdp** [SingularSound/openbbm#69]
Hi I successfully ran the windows release deployment of bbm but I had to add a couple of steps:

Before building, remove `debug` from

https://github.com/SingularSound/openbbm/blob/6755d60ba5827598e393f4752395aeaec5ff1de5/BBManagerLean/BBManagerLean.pro#L3

I suspect this could be done conditionally based on build config?

Then after running `windeployqt.exe --quick .` I needed to manually copy the minIni and quazip libraries from the libs directory (in my case for msvc_64) into the folder containing the exe.

**Comment by iajrz** [comment]
docs are slated do change - an update based on setting up a computer from scratch was made recently. This issue is likely outdated.
