### ISSUE TITLE
Pick notes of a fill (notes that happen just before the main bar of a fill) are not being played when triggered by autopilot.

### ISSUE THREAD

**Issue by JulissaDantes** [SingularSound/openbbm#7]
Pick notes of a fill (notes that happen just before the main bar of a fill) are not being played when triggered by autopilot. The main fill bar should be played in the bar in which it was specified, but the pick up notes should also be played in the preceding bar. Explanation: A regular loop, such a normal beat will start at the beginning of a bar and end at the end of the bar. Everything fits within the boundaries of a bar. However, sometimes in music, whether it is a melody or a drum fill, we may have notes that preceed the bar. They happen before the beginning of a bar. Think of The Beatles lyrics: "All we need is Love". "All we need is" is sang before the beginning of the first bar and word "Love" happens on the beat one of the 1st bar. So, that first part of the sentence is a 'pick up'.

**Comment by Kiroto** [comment]
Could not reproduce:
Edited a beat so it's pick beat is distinguishable.
Set auto pilot to trigger transition when the loop ends.
The loop ended (the pick note played successfully) and the transition triggered correctly.

**Comment by JulissaDantes** [comment]
Include here: When playing the midi, as a single track, is not playing pick up notes.
