### ISSUE TITLE
Transition Fill not playing additional bars

### ISSUE THREAD

**Issue by JulissaDantes** [SingularSound/openbbm#72]
Transition fill.
BUG- "Additional [ ] bars" is not working right now. It only plays transition fill for the duration of the loaded file, regardless of the settings.

**Comment by JulissaDantes** [comment]
We are forgoing "play additional" and only specifying the actual, exact number of bars transition fill should play for. If the setting is 1, it should play for 1 bar. If the setting is 2, it should play for 2 bars. 

Since we have an off switch (checkmark), perhaps we should disable 0 and the minimum be 1.

**Comment by JulissaDantes** [comment]
This is ready on the Issue72 branch @Kiroto

**Comment by Kiroto** [comment]
Tested on branch 7, looks good to me!
