### ISSUE TITLE
Change Main/Trans Fill label on condition

### ISSUE THREAD

**Issue by JulissaDantes** [SingularSound/openbbm#73]
Once the main loop is set with AP (check-marked), then transition AP checkmark should also appear along with "Play for [x] bars" by default. The x should be the total number of bars that is present in the loaded file. (If the file is changed, then x should update to reflect the number of bars of the new file.) Users can then leave it 'as is' for the transition to play for the full number of bars for that file, or set a higher or lower number of bars. In any scenario, it should play the total number of bars presented in the box/ set by the user.

If transition fill AP is un-checked, then "Play for [_] bars" disappears and text displays "Manual Trigger Only". At the same time, the main loop text changes from "Transition Fill at bar []" to "Play for [] bars". This will allow a transition fill to remain loaded and available for manual trigger, without being automatically played.

**Comment by JulissaDantes** [comment]
@Kiroto This is ready to be tested on 'Issue77' branch.

**Comment by Kiroto** [comment]
Tested, looking good!
