### ISSUE TITLE
Change last main fill label if outro exists

### ISSUE THREAD

**Issue by JulissaDantes** [SingularSound/openbbm#77]
If Outro Fill is loaded, change text of the final main loop to "Play Outro Fill At Bar []". If there is a transition fill loaded, then the text will stay as "Transition Fill at Bar []". If AP is off for that part, it should say "Loop Indefinitely". If there are no transition fill and no outro fill loaded, AP should say "End after [] bars".

**Comment by JulissaDantes** [comment]
This is every possible label for the last part main fill for the updateAPText method:
Main Label | hasMain | hasTran | hasOutro
------------ | ------------- | ------------ | -------------
Transition Fill at Bar []| 1|1|1
Play Outro Fill At Bar []| 1|0|1
Transition Fill at Bar []| 1|1|0
End after [] bars| 1|0|0
Loop Indefinitely| 0|1|1
Loop Indefinitely| 0|0|1
Loop Indefinitely| 0|1|0
Loop Indefinitely| 0|0|0

**Comment by JulissaDantes** [comment]
@Kiroto You can test this on the branch with the same name

**Comment by Kiroto** [comment]
Label that says "End after [] bars" instead says "End after bars []". Otherwise, all good.

**Comment by Kiroto** [comment]
All looks good to me now!
