### ISSUE TITLE
Making the warning about songs containing a section without a main drum loop text more user-friendly.

### ISSUE THREAD

**Issue by JulissaDantes** [SingularSound/openbbm#8]
When trying to open a saved project with a song containing a section without any fill, like this:
![image](https://user-images.githubusercontent.com/8561085/78377037-1b815f00-759d-11ea-9a6e-f96d7667d56c.png)
The following error shows up:
![image](https://user-images.githubusercontent.com/8561085/78376842-deb56800-759c-11ea-9ee4-bb5a7b35b5f7.png)

**Comment by JulissaDantes** [comment]
That is only when there is no main loop in a song section.  Every song section needs a main loop, so the warning is valid. A **solution** would be making the error message a custom one, so the user always knows what to do.

**Comment by Kiroto** [comment]
This error does not always show:
In this instance, I got the error the first time, but no more.
![image](https://user-images.githubusercontent.com/11585686/80498638-f8e32b80-8939-11ea-8439-d801adf831be.png)

**Comment by JulissaDantes** [comment]
Unable to reproduce as well, there must be another condition triggering this warning.
