### ISSUE TITLE
Dead Links on Contributing Guidelines

### ISSUE THREAD

**Issue by brennansingular** [SingularSound/openbbm#86]
[Hyperlinks on "issues"](https://github.com/SingularSound/openbbm/blob/master/CONTRIBUTING.md) go to the old archived BBM repo instead of the current open BBM repo.

![Screen Shot 2020-07-21 at 3 40 17 PM](https://user-images.githubusercontent.com/62663388/88117890-48787280-cb8a-11ea-959e-a0314ac3d66b.png)

**Comment by JulissaDantes** [comment]
The links were updated in master.
